### ISSUE TITLE
MEETS_DEVICE_INTEGRITY not passing after updating to v15.9.9

### ISSUE THREAD

**Issue by iCelo-git** [chiteroman/PlayIntegrityFix#329] opened 2024-05-23 09:50 UTC
I'm running currently Tequilla OS Android 13 on my Xiaomi Mi 10.
I realized that MEETS_DEVICE_INTEGRITY isn't passing and CTS profile math is failing today. So I checked the repo for the new version. I saw that v15.9.9 is released 10 min ago. 😄 I had a simillar situation a week ago and it was fixed after the update to v15.9.8. Unfortunetly after updating to v15.9.9 there is not the case anymore 😢

What logs can I provide to make it easier to resolve this issue?

**Comment by crok** [comment] 2024-05-23 09:55
I can confirm the above, PIF v15.9.9 with the included fingerprint fails on my devices as well (ArrowOS).

**Comment by paveltar** [comment] 2024-05-23 09:59
Same here, running MIUI 14 - Xiaomi.eu on Mi 11 Ultra

**Comment by chiteroman** [comment] 2024-05-23 10:12
Do you have playcurl module? Remove it and then install PIF.
https://t.me/playintegrityfix/40

**Comment by paveltar** [comment] 2024-05-23 10:15
> Do you have playcurl module? Remove it and then install PIF. https://t.me/playintegrityfix/40

The issue is fixed for me now (probably after automatic playcurl update triggered).

**Comment by iCelo-git** [comment] 2024-05-23 10:29
> Do you have playcurl module? Remove it and then install PIF. https://t.me/playintegrityfix/40

I've just learnt that there is something like playcurl. To test things out I tried:
- Reinstalling PIF (Removing from Magisk -> Reboot -> Installing newest .zip -> Reboot) -> Not passing
- Installing playcurl alongside PIF after the reinstallation of PIF -> Not passing

**Comment by ionutgherman** [comment] 2024-05-23 10:35
MEETS_DEVICE_INTEGRITY not passing if you're running custom ROMs. apparently, Google added custom ROM detection. Must be fun to them, I guess

**Comment by SaleOff** [comment] 2024-05-23 13:24
me too CrDroid v7.20 Android 11

**Comment by Affan-Shakoor** [comment] 2024-05-23 13:55
Fail integrity on project blaze Android 14 security patch. May

**Comment by donutnotnut** [comment] 2024-05-23 16:09
Nope, custom rom not passing

**Comment by davemmi** [comment] 2024-05-23 16:16
customized miui rom is passing (greeshan miui mod, Poco F5)

**Comment by paveltar** [comment] 2024-05-23 16:19
> > MEETS_DEVICE_INTEGRITY not passing if you're running custom ROMs. apparently, Google added custom ROM detection. Must be fun to them, I guess
> 
> Really?
> 
> Anyone passing on custom rom?

Passing on MIUI 14 - Xiaomi.eu with Mi 11 Ultra, with reinstalled PIF 15.9.9 and playcurl. seconds.txt set to 600 (10 minutes).

**Comment by kkazakov** [comment] 2024-05-23 16:20
AOSP not passing

**Comment by LuckyTheCookie** [comment] 2024-05-23 16:36
Custom rom not passing

**Comment by MaccabeeY** [comment] 2024-05-23 18:20
LineageOS A13 not passing (plus getting "token from Google - transient error" too)

**Comment by Yurysub** [comment] 2024-05-23 18:25
AlfaDroid A13 не проходит

**Comment by Yurysub** [comment] 2024-05-23 18:27
AlfaDroid A13 does not work

**Comment by Adiker** [comment] 2024-05-23 20:51
PixelStar on Poco F4 (KernelSU) - not passing
AOSPA 14 on OnePlus 9 Pro (Magisk) - passing.
Weird.

**Comment by dularacharith** [comment] 2024-05-24 05:17
I'm currently using .8 and it passes the integrity check in basic. I guess the problem is my custom rom. Did any one fix this issue?

**Comment by dandocmando** [comment] 2024-05-24 05:38
I'm on nameless a13, not passing.

**Comment by tomeczeka** [comment] 2024-05-24 06:20
After updating to .9 it worked for me once, but doesn't anymore today. CherishOS on sweet

**Comment by tomeczeka** [comment] 2024-05-24 07:17
> MEETS_DEVICE_INTEGRITY not passing if you're running custom ROMs. apparently, Google added custom ROM detection. Must be fun to them, I guess

I don't quite get how they don't understand that even with bootloader unlocked and root access, a device of a person who cared enough to do that is safer than a normie device with stock rom.

**Comment by MiMillieuh** [comment] 2024-05-24 09:04
Can confirm it's not working on CRdroid either. 

But for real I just need MEETS_DEVICE_INTERGRITY for Google Pay guess I'll use a real credit card for now...

It has worked for some random periods yesterday but it's not working at all today.

**Comment by e0003** [comment] 2024-05-24 10:00
Confirmed 15.9.9 failed CTS Profile Match
version 15.9.8 and the version before worked
The device do not have either playcurl module nor /data/adb/pif.json all this while and attestation just worked.
So something must have broken again in version 15.9.9

**Comment by Hunsu** [comment] 2024-05-24 15:11
I pass the integrity check, but Google Wallet no longer works. Other apps do not seem to detect the root, though.

**Comment by dandocmando** [comment] 2024-05-24 21:59
> > I pass the integrity check and SefetyNet, but Google Wallet no longer works. Other apps do not seem to detect the root, though.
> 
> Same here: play integrity check apps pass, my banking app passes, but Wallet says "your device doesn't meet security requirements" 🤔
> 
> Running Paranoid Uvite on Poco F5 by the way. 

If you pass device integrity, wiping google wallet should fix it.

**Comment by tarockx** [comment] 2024-05-24 22:02
> > > I pass the integrity check and SefetyNet, but Google Wallet no longer works. Other apps do not seem to detect the root, though.
> > 
> > 
> > Same here: play integrity check apps pass, my banking app passes, but Wallet says "your device doesn't meet security requirements" 🤔
> > Running Paranoid Uvite on Poco F5 by the way.
> 
> If you pass device integrity, wiping google wallet should fix it.

Just tried, didn't work...

**Comment by rogergithubbing** [comment] 2024-05-24 22:27
Not working on mi mix 2 with crdroid 9.12 ( Android 13)

**Comment by Jon8RFC** [comment] 2024-05-25 04:02
> Just tried, didn't work...

I'm curious what your Google play store status is...
Settings>about>very bottom "play protect certification"

**Comment by Hunsu** [comment] 2024-05-25 05:36
> @tarockx
> I'm curious what your Google play store status is... Settings>about>very bottom "play protect certification"

It says Device is certified for me.

**Comment by franz-dc** [comment] 2024-05-25 08:58
Downgrading to 15.

**Comment by UnsuitableFollower** [comment] 2024-05-25 10:53
same here, 15.9.8 safetynet passed

**Comment by tarockx** [comment] 2024-05-25 12:41
> @tarockx
> 
> > Just tried, didn't work...
> 
> I'm curious what your Google play store status is... Settings>about>very bottom "play protect certification"

Well, since this morning Wallet says that everything is good again. I guess maybe it "caches" the certification status and only updates it once a day or something like that? 🤔

**Comment by dandocmando** [comment] 2024-05-25 12:47
> > @tarockx
> > 
> > > Just tried, didn't work...
> > 
> > I'm curious what your Google play store status is... Settings>about>very bottom "play protect certification"
> 
> Well, since this morning Wallet says that everything is good again. I guess maybe it "caches" the certification status and only updates it once a day or something like that? 🤔

Yeah it does cache for 24h, wiping the wallet usually resets it. Weird that you are passing on a custom ROM and the rest of us aren't.

**Comment by Hunsu** [comment] 2024-05-25 12:51
> > > @tarockx
> > > > Just tried, didn't work...
> > > 
> > > 
> > > I'm curious what your Google play store status is... Settings>about>very bottom "play protect certification"
> > 
> > 
> > Well, since this morning Wallet says that everything is good again. I guess maybe it "caches" the certification status and only updates it once a day or something like that? 🤔
> 
> Yeah it does cache for 24h, wiping the wallet usually resets it. Weird that you are passing on a custom ROM and the rest of us aren't.

You mean clearing cache? Because it doesn't work for me doing so?

**Comment by dandocmando** [comment] 2024-05-25 12:52
> > > > @tarockx
> > > > > Just tried, didn't work...
> > > > 
> > > > 
> > > > I'm curious what your Google play store status is... Settings>about>very bottom "play protect certification"
> > > 
> > > 
> > > Well, since this morning Wallet says that everything is good again. I guess maybe it "caches" the certification status and only updates it once a day or something like that? 🤔
> > 
> > Yeah it does cache for 24h, wiping the wallet usually resets it. Weird that you are passing on a custom ROM and the rest of us aren't.
> 
> You mean clearing cache? Because it doesn't work for me doing so? 

No, clearing both cache and data for the wallet app.

**Comment by paveltar** [comment] 2024-05-25 12:55
For me, the wallet warning doesn't mean I can pay our not, only DEVICE_INTEGRITY does

**Comment by Hunsu** [comment] 2024-05-25 12:57
I see now that I no longer meet device integrity.

**Comment by dandocmando** [comment] 2024-05-25 12:58
> For me, the wallet warning doesn't mean I can pay our not, only DEVICE_INTEGRITY does

The wallet warning doesn't appear immediately, I always check integrity before only taking my phone somewhere.

**Comment by MiMillieuh** [comment] 2024-05-25 13:10
> > For me, the wallet warning doesn't mean I can pay our not, only DEVICE_INTEGRITY does
> 
> The wallet warning doesn't appear immediately, I always check integrity before only taking my phone somewhere.

It appears when you open wallet let it for a few seconds and close it and reopen it. I got the message 100% of time when I don't pass integrity with this method

**Comment by tarockx** [comment] 2024-05-25 14:43
> > > > @tarockx
> > > > > Just tried, didn't work...
> > > > 
> > > > 
> > > > I'm curious what your Google play store status is... Settings>about>very bottom "play protect certification"
> > > 
> > > 
> > > Well, since this morning Wallet says that everything is good again. I guess maybe it "caches" the certification status and only updates it once a day or something like that? 🤔
> > 
> > 
> > Yeah it does cache for 24h, wiping the wallet usually resets it. Weird that you are passing on a custom ROM and the rest of us aren't.
> 
> No Google Wallet warning does not mean it will work at a store

I've just tried a contactless payment in an actual shop and it worked 👍 so it appears that the warning message from wallet was indeed just cached.

Some further info if it is of any help:
- Running PIF 15.9.9 through KernelSU (Zygisk Next 1.0.5)
- Running Paranoid Android 14 "Uvite" on Poco F5 (codename marble)
- Kernel signature is "5.10.209-android12-9-02794-g280193753c44-ab11734656", boot image is patched to run KernelSU
- I don't have a custom /data/adb/pif.json file
- I don't have the playcurl module installed

**Comment by Elerir** [comment] 2024-05-25 19:32
Fresh A14 Watchdogs on OP9 not passing device integrity

**Comment by chiteroman** [comment] 2024-05-26 02:10
AOSP roms must be signed to pass Device verdict.

Ask your ROM maintainer about it.

**Closed by chiteroman** 2024-05-26 02:10 UTC

**Comment by MaccabeeY** [comment] 2024-05-27 03:10
> LineageOS A13 not passing (plus getting "token from Google - transient error" too)

Something interesting (interesting to me) happened today & an idea hit me.

So the story goes as follows:

A number of days, without changing anything on the phone, (always checking to see if Play Store was current) DEVICE started to fail, at which point I updated to 15.9.9.  Then a few days after that, I kept getting the "transient error" so couldn't even check anymore.  Now during all this, Play Store reported itself as "uptodate" (no new Play Store updates during this period).

Then earlier this morning, when I want to check for DEVICE, Play Store reported an update available so I update.  So I then checked again and VIOLA, I passed bother BASIC/DEVICE & BASIC/CTS.


Idea:

So this evening it hit that maybe Google changed things on their "backend" without issuing a corresponding functional update to their Play Store, taking days to finally realize their mistake...that their backend introduced breaking changes upon their Play Store which to bring Play Store out of breakage.

If there is any reality to this hypothesis, we've may have been "banging our heads" over the recent DEVICE failure when it had been an "out-of-sync" Google "cluster-f*** " the whole time.

Have no concrete evidence to support this hypothesis but events seemed a follow as a logical induction, so I thought I'd share.

**Comment by rogergithubbing** [comment] 2024-05-27 06:13
> > LineageOS A13 not passing (plus getting "token from Google - transient error" too)
> 
> Something interesting (interesting to me) happened today & an idea hit me.
> 
> So the story goes as follows:
> 
> A number of days, without changing anything on the phone, (always checking to see if Play Store was current) DEVICE started to fail, at which point I updated to 15.9.9. Then a few days after that, I kept getting the "transient error" so couldn't even check anymore. Now during all this, Play Store reported itself as "uptodate" (no new Play Store updates during this period).
> 
> Then earlier this morning, when I want to check for DEVICE, Play Store reported an update available so I update. So I then checked again and VIOLA, I passed bother BASIC/DEVICE & BASIC/CTS.
> 
> Idea:
> 
> So this evening it hit that maybe Google changed things on their "backend" without issuing a corresponding functional update to their Play Store, taking days to finally realize their mistake...that their backend introduced breaking changes upon their Play Store which to bring Play Store out of breakage.
> 
> If there is any reality to this hypothesis, we've may have been "banging our heads" over the recent DEVICE failure when it had been an "out-of-sync" Google "cluster-f*** " the whole time.
> 
> Have no concrete evidence to support this hypothesis but events seemed a follow as a logical induction, so I thought I'd share.

I have tested this in my device (chiron, crdroid) with no luck 8-/

**Comment by tazaxer** [comment] 2024-05-27 06:51
how can we tell if the rom is signed without having to ask the maintainer?

(Same issue, running PixelOS, Xiaomi Mi9T)
